sudo: false

language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4'
- '5'
- '6'
- '7'
- iojs

cache:
  directories:
    - node_modules

after_script: 'gulp coveralls'

notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5